language: node_js
node_js:
  - "8"

#install:
#  - npm install
#  - npm install -g codecov
#  - npm install -g istanbul
#
#script:
#  - istanbul cover ./node_modules/mocha/bin/_mocha -R lcovonly -R spec
#  - codecov

deploy:
  provider: npm
  email: $EMAIL
  api_key: $API_KEY